# Generated by Django 5.2 on 2025-07-20 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hot_sale', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.CharField(blank=True, choices=[('rayban', 'Rayban'), ('gucci', 'Gucci'), ('tomford', 'Tom Ford'), ('armani', 'Emporio Armani'), ('dior', 'Dior'), ('prada', 'Prada'), ('police', 'Police'), ('lacoste', 'Lacoste'), ('burberry', 'Burberry'), ('givenchy', 'Givenchy'), ('fendi', 'Fendi'), ('boss', 'Hugo Boss'), ('cartier', 'Cartier'), ('chanel', 'Chanel'), ('valentino', 'Valentino'), ('celine', 'Celine'), ('vogue', 'Vogue Eyewear'), ('montblanc', 'Montblanc'), ('tiffany', 'Tiffany & Co.'), ('dita', 'Dita'), ('jacques_mare_mage', 'JACQUES MARE MAGE'), ('john_dalia', 'JOHN Dalia'), ('philipp_plein', 'Philipp Plein'), ('moscot', 'Moscot')], max_length=50, null=True)),
                ('main_category', models.CharField(choices=[('SUNGLASSES', 'SUNGLASSES'), ('OPTICAL', 'OPTICAL'), ('JEANSCLUB', 'JEANSCLUB'), ('CLIP-ON', 'CLIP-ON')], max_length=20)),
                ('sub_category', models.CharField(blank=True, choices=[('SUNGLASSES', 'SUNGLASSES'), ('OPTICAL', 'OPTICAL')], max_length=20, null=True)),
                ('image', models.CharField(max_length=255)),
                ('age_group', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=70, max_digits=6)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PROCESSING', 'تم التحضير'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التوصيل'), ('CANCELLED', 'تم الإلغاء')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('instapay', 'Instapay'), ('visa', 'Visa / MasterCard'), ('Cash', 'Cash on Delivery')], default='Cash', max_length=20)),
                ('government', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.government')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_color', models.URLField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_color', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('color_name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
