# Generated by Django 5.2 on 2025-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_color',
            field=models.URLField(blank=True, null=True),
        ),
    ]
