# Generated by Django 5.2 on 2025-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_selected_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(choices=[('instapay', 'Instapay'), ('visa', 'Visa / MasterCard'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
