# Generated by Django 5.2 on 2025-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(choices=[('instapay', 'Instapay'), ('visa', 'Visa / MasterCard'), ('Cash', 'Cash on Delivery')], default='Cash', max_length=20),
        ),
    ]
