# Generated by Django 5.2 on 2025-04-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_code',
        ),
    ]
