# Generated by Django 5.2 on 2025-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'Visa'), ('cod', 'الدفع عند الاستلام')], default='cod', max_length=10),
        ),
    ]
