# Generated by Django 5.2 on 2025-04-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customerorder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='payment_method',
        ),
    ]
