# Generated by Django 5.2 on 2025-04-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_customerorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
