# Generated by Django 5.2 on 2025-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_sale',
            field=models.BooleanField(default=False),
        ),
    ]
