# Generated by Django 5.2 on 2025-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customerorder_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PROCESSING', 'تم التحضير'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التوصيل'), ('CANCELLED', 'تم الإلغاء')], default='PENDING', max_length=20),
        ),
    ]
