# Generated by Django 5.2 on 2025-04-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customerorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='products',
        ),
    ]
