# Generated by Django 5.2 on 2025-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('rayban', 'Rayban'), ('gucci', 'Gucci'), ('tomford', 'Tom Ford'), ('versace', 'Versace'), ('armani', 'Emporio Armani'), ('dior', 'Dior'), ('prada', 'Prada'), ('oakley', 'Oakley'), ('police', 'Police'), ('lacoste', 'Lacoste'), ('maui_jim', 'Maui Jim'), ('burberry', 'Burberry'), ('givenchy', 'Givenchy'), ('fendi', 'Fendi'), ('boss', 'Hugo Boss'), ('cartier', 'Cartier'), ('chanel', 'Chanel'), ('balenciaga', 'Balenciaga'), ('miu_miu', 'Miu Miu'), ('valentino', 'Valentino'), ('celine', 'Celine'), ('coach', 'Coach'), ('vogue', 'Vogue Eyewear'), ('montblanc', 'Montblanc'), ('tiffany', 'Tiffany & Co.'), ('Dita', ' Dita'), ('JACQUES MARE MAGE', ' JACQUES MARE MAGE'), ('JOHN Dalia', ' JOHN Dalia'), ('philipp plein ', ' philipp plein'), ('Tomford', 'Tomford'), ('Moscot', 'Moscot')], default='rayban', max_length=50),
        ),
    ]
