# Generated by Django 5.2 on 2025-04-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
