# Generated by Django 5.2 on 2025-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('rayban', 'Rayban'), ('gucci', 'Gucci'), ('tomford', 'Tom Ford'), ('versace', 'Versace'), ('armani', 'Emporio Armani'), ('dior', 'Dior'), ('prada', 'Prada'), ('oakley', 'Oakley'), ('police', 'Police'), ('lacoste', 'Lacoste'), ('maui_jim', 'Maui Jim'), ('burberry', 'Burberry'), ('givenchy', 'Givenchy'), ('fendi', 'Fendi'), ('boss', 'Hugo Boss'), ('cartier', 'Cartier'), ('chanel', 'Chanel'), ('balenciaga', 'Balenciaga'), ('miu_miu', 'Miu Miu'), ('valentino', 'Valentino'), ('celine', 'Celine'), ('coach', 'Coach'), ('vogue', 'Vogue Eyewear'), ('montblanc', 'Montblanc'), ('tiffany', 'Tiffany & Co.'), ('dita', 'Dita'), ('jacques_mare_mage', 'JACQUES MARE MAGE'), ('john_dalia', 'JOHN Dalia'), ('philipp_plein', 'Philipp Plein'), ('moscot', 'Moscot')], max_length=50, null=True),
        ),
    ]
