# Generated by Django 5.2 on 2025-06-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('rayban', 'Rayban'), ('gucci', 'Gucci'), ('tomford', 'Tom Ford'), ('armani', 'Emporio Armani'), ('dior', 'Dior'), ('prada', 'Prada'), ('police', 'Police'), ('lacoste', 'Lacoste'), ('burberry', 'Burberry'), ('givenchy', 'Givenchy'), ('fendi', 'Fendi'), ('boss', 'Hugo Boss'), ('cartier', 'Cartier'), ('chanel', 'Chanel'), ('valentino', 'Valentino'), ('celine', 'Celine'), ('vogue', 'Vogue Eyewear'), ('montblanc', 'Montblanc'), ('tiffany', 'Tiffany & Co.'), ('dita', 'Dita'), ('jacques_mare_mage', 'JACQUES MARE MAGE'), ('john_dalia', 'JOHN Dalia'), ('philipp_plein', 'Philipp Plein'), ('moscot', 'Moscot')], max_length=50, null=True),
        ),
    ]
