BRAND_CHOICES = [
    ('rayban', 'Rayban'),
    ('gucci', 'Gucci'),
    ('tomford', 'Tom Ford'),
    # ('versace', 'Versace'),
    ('armani', 'Emporio Armani'),
    ('dior', 'Dior'),
    ('prada', 'Prada'),
    # ('oakley', 'Oakley'),
    ('police', 'Police'),
    ('lacoste', 'Lacoste'),
    # ('maui_jim', 'Maui Jim'),
    ('burberry', 'Burberry'),
    ('givenchy', 'Givenchy'),
    ('fendi', 'Fendi'),
    ('boss', 'Hugo Boss'),
    ('cartier', 'Cartier'),
    ('chanel', 'Chanel'),
    # ('balenciaga', 'Balenciaga'),
    # ('miu_miu', 'Miu Miu'),
    ('valentino', 'Valentino'),
    ('celine', 'Celine'),
    # ('coach', 'Coach'),
    ('vogue', 'Vogue Eyewear'),
    ('montblanc', 'Montblanc'),
    ('tiffany', 'Tiffany & Co.'),
    ('dita', 'Dita'),
    ('jacques_mare_mage', 'JACQUES MARE MAGE'),
    ('john_dalia', 'JOHN Dalia'),
    ('philipp_plein', 'Philipp Plein'),
    ('moscot', 'Moscot'),
]
